### PR TITLE
added JSDOM instead of Node support for elems as an experiment

### PR DESCRIPTION
**Pull request by janzheng**
Doing this makes it work for Deno, but absolutely breaks browser support. This was also refactored with Claude and I had to fix/patch some weird inconsistencies, so PLEASE DON'T MERGE THIS AS IS!

Probably the best way to do this is to have a third non-Node build that uses JSDOM instead of relying on Node types, which prevents it from working in Deno (https://news.ycombinator.com/item?id=41047445), but that's not what I did in this PR...

### CODE REVIEW

**Comment by romansky** [comment]
Hi @janzheng, thanks for following up and this sounds interesting!
My bad for not including a style guide / lint configuration.. Thing is, I can't really tell what changes have been made since your pull changed indentation of all sources.. Any chance for an easy fix on your side?

**Comment by janzheng** [comment]
haha I guess that's the problem with using Claude. Thankfully Claude can help us diff... The only real changes are in this file, where I removed all references to Node:
`htmlToMarkdownAST.ts`: (Claude diff: https://claude.site/artifacts/7af5d198-2b1b-4900-a403-feea7b1dd132)
- Changing `childElement.nodeType === Node.TEXT_NODE` to `childElement.nodeType === childElement.TEXT_NODE` so we're not dependent on Node
- Claude also insisted on editing the table element to only prefer `content: htmlToMarkdownAST(cell as Element, options, indentLevel + 1),` — I quickly tested it but couldn't find any difference in output

`domUtils.ts`: ignore this one; none of the changes affect conversion

I noticed that in my outputs I get `<-header->` tags, which is from `markdownASTToString.ts:202` but for some reason your examples aren't showing these headers?

```
<-header->


<-nav->
 [Home](/) [Blog](/blog/) [About](/about/)

</-nav->
# SoftwareYoga

Articles on Coding and Architecture



</-header->

```

**Comment by romansky** [comment]
It's still hard to know what changes have been made :(
So please cleanup the pull request reverting unwanted changes..

Does this make sense? -
As I am not familiar with Deno, if we are looking for proper support for it in addition to Node (and as you say they are not compatible), please check out `examples/cli` where we build and publish the cli version `n2m` on every new version in addition to the NPM package in the root. Copy it and create `examples/deno` where you can make all the relevant changes to be able to publish and run a Deno compatible version.


Re- "<-header->", do you mean you are running some code from the examples and its producing a different output? Please let me know how to reproduce.

**Comment by lukasb** [comment]
> On my end, this worked just fine with Bun.
> 
> ```ts
> function setupDOMPolyfill() {
>   const dom = new JSDOM("<!DOCTYPE html><html><body></body></html>");
> 
>   // Polyfill global objects if they don't exist
>   if (typeof global.window === "undefined") global.window = dom.window as any;
>   if (typeof global.document === "undefined")
>     global.document = dom.window.document;
>   if (typeof global.Node === "undefined") global.Node = dom.window.Node;
>   if (typeof global.Element === "undefined")
>     global.Element = dom.window.Element;
>   if (typeof global.HTMLElement === "undefined")
>     global.HTMLElement = dom.window.HTMLElement;
>   if (typeof global.DOMParser === "undefined")
>     global.DOMParser = dom.window.DOMParser;
> }
> 
> // Call the polyfill setup function
> setupDOMPolyfill();
> ```

worked for me with Next.js as well

**Comment by janzheng** [comment]
I'm running these server-side on Deno, so I don't have access to `global` — but the issue I'm running into is Deno's lack of `Node` which means I can't compare `Node.TEXT_NODE`:
```
Uncaught (in promise) ReferenceError: Node is not defined
        } else if (childElement.nodeType === Node.TEXT_NODE) {
```

But apparently it's an easy fix (ignore my pull request). Apparently I can just replace any Node.TEXT_NODE with `3`, and Node.ELEMENT_NODE with `1` (https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType) e.g. and it works.
```
} else if (childElement.nodeType === 3) {

instead of

} else if (childElement.nodeType === Node.TEXT_NODE) {
```


I also had to make a quick change to`/src/index.ts`: (added "type" after import, otherwise it wouldn't import properly)
```
import type {ConversionOptions, SemanticMarkdownAST} from './types/markdownTypes';
```

**Comment by romansky** [comment]
@janzheng following your example, I added the Node constants via library local _Node object and added the `type` import, if possible, please try the latest version and let me know if it works for you

**Comment by janzheng** [comment]
Seems to still rely on Node; here's a live example: https://www.val.town/v/yawnxyz/denoDom2SemExample

**Comment by romansky** [comment]
@janzheng cool site! 
Looks like it's working with a later version here's my fork: https://www.val.town/v/romansky/denoDom2SemExample

**Comment by janzheng** [comment]
fantastic, thanks so much for your hard work!!

**Comment by BrianHung** [comment]
Thanks for the quick fix; this library works for cloudflare puppeter with `linkedom` as the DOM Parser now!

**Pull request closed without merging**
